// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CwppsOY0-JxcjMO0QOgH0i88y0ab8qI',
    appId: '1:556013697245:web:8dc97bb9694eeb25200334',
    messagingSenderId: '556013697245',
    projectId: 'ludo-dd19a',
    authDomain: 'ludo-dd19a.firebaseapp.com',
    databaseURL: 'https://ludo-dd19a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-dd19a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbpygmsl0uiEZwY6oBQ44xNQAKtRqY3A',
    appId: '1:556013697245:android:bb4be7d476b6ca34200334',
    messagingSenderId: '556013697245',
    projectId: 'ludo-dd19a',
    databaseURL: 'https://ludo-dd19a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-dd19a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGPWNjuV3-I4vQOWrnElNnnEAcptKyt4E',
    appId: '1:556013697245:ios:9e3cd0930b273b21200334',
    messagingSenderId: '556013697245',
    projectId: 'ludo-dd19a',
    databaseURL: 'https://ludo-dd19a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ludo-dd19a.firebasestorage.app',
    androidClientId: '556013697245-tnqro2k2ec3ebegjocf9qfl1v879iv86.apps.googleusercontent.com',
    iosClientId: '556013697245-irfm6hu78cbnjtjuumer4lkad1kg3uij.apps.googleusercontent.com',
    iosBundleId: 'com.ludo.iosApp',
  );
}
